### ISSUE TITLE
The vocab attribute was removed from KeyedVector in Gensim 4.0.0.

### ISSUE THREAD

**Issue by CWQFT** [marcopodda/fragment-based-dgm#4]
Hi, I have a issue. I have gensim 4.3.1 installed. Here is the error message encountered while training:
Training and clustering embeddings... Traceback (most recent call last):
  File "/home/user1/data/zwh/fragment-based-dgm-master/learner/dataset.py", line 77, in get_vocab
    self.vocab = Vocab.load(self.config)
  File "/home/user1/data/zwh/fragmHi, I have a issue. I have gensim 4.3.1 installed. Here is the error message encountered while training:
Training and clustering embeddings... Traceback (most recent call last):
  File "/home/user1/data/zwh/fragment-based-dgm-master/learner/dataset.py", line 77, in get_vocab
    self.vocab = Vocab.load(self.config)
  File "/home/user1/data/zwh/fragment-based-dgm-master/learner/skipgram.py", line 22, in load
    return load_pickle(path)
  File "/home/user1/data/zwh/fragment-based-dgm-master/utils/filesystem.py", line 8, in load_pickle
    return pkl.load(open(path, "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'RUNS/2023-06-28@07:57:32-b44d3a1aad14-ZINC/config/vocab.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/data/zwh/fragment-based-dgm-master/manage.py", line 59, in <module>
    train_model(config)
  File "/home/user1/data/zwh/fragment-based-dgm-master/manage.py", line 18, in train_model
    vocab = dataset.get_vocab()
  File "/home/user1/data/zwh/fragment-based-dgm-master/learner/dataset.py", line 79, in get_vocab
    self.vocab = Vocab(self.config, self.data)et_vocab
    self.vocab = Vocab(self.config, self.data)
  File "/home/user1/data/zwh/fragment-based-dgm-master/learner/skipgram.py", line 34, in  __init__
    train_embeddings(config, data)    __init__
    train_embeddings(config, data)
  File "/home/user1/data/zwh/fragment-based-dgm-master/learner/skipgram.py", line 142, in train_embeddings
    vocab = w2v.wv.vocab
  File "/home/user/anaconda3/envs/aistats2020/lib/python3.11/site-packages/gensim/models/keyedvectors.py", line 734, in vocab
    raise AttributeError(
AttributeError: The vocab attribute was removed from KeyedVector in Gensim 4.0.0.
Use KeyedVector's .key_to_index dict, .index_to_key list, and methods .get_vecattr(key, attr) and .set_vecattr(key, attr, new_val) instead.
See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4

I wonder how to fix this? Thank you

**Comment by liang2508** [comment]
> Hi, I have a issue. I have gensim 4.3.1 installed. Here is the error message encountered while training: Training and clustering embeddings... Traceback (most recent call last): File "/home/user1/data/zwh/fragment-based-dgm-master/learner/dataset.py", line 77, in get_vocab self.vocab = Vocab.load(self.config) File "/home/user1/data/zwh/fragmHi, I have a issue. I have gensim 4.3.1 installed. Here is the error message encountered while training: Training and clustering embeddings... Traceback (most recent call last): File "/home/user1/data/zwh/fragment-based-dgm-master/learner/dataset.py", line 77, in get_vocab self.vocab = Vocab.load(self.config) File "/home/user1/data/zwh/fragment-based-dgm-master/learner/skipgram.py", line 22, in load return load_pickle(path) File "/home/user1/data/zwh/fragment-based-dgm-master/utils/filesystem.py", line 8, in load_pickle return pkl.load(open(path, "rb")) FileNotFoundError: [Errno 2] No such file or directory: 'RUNS/2023-06-28@07:57:32-b44d3a1aad14-ZINC/config/vocab.pkl'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/user1/data/zwh/fragment-based-dgm-master/manage.py", line 59, in train_model(config) File "/home/user1/data/zwh/fragment-based-dgm-master/manage.py", line 18, in train_model vocab = dataset.get_vocab() File "/home/user1/data/zwh/fragment-based-dgm-master/learner/dataset.py", line 79, in get_vocab self.vocab = Vocab(self.config, self.data)et_vocab self.vocab = Vocab(self.config, self.data) File "/home/user1/data/zwh/fragment-based-dgm-master/learner/skipgram.py", line 34, in **init** train_embeddings(config, data) **init** train_embeddings(config, data) File "/home/user1/data/zwh/fragment-based-dgm-master/learner/skipgram.py", line 142, in train_embeddings vocab = w2v.wv.vocab File "/home/user/anaconda3/envs/aistats2020/lib/python3.11/site-packages/gensim/models/keyedvectors.py", line 734, in vocab raise AttributeError( AttributeError: The vocab attribute was removed from KeyedVector in Gensim 4.0.0. Use KeyedVector's .key_to_index dict, .index_to_key list, and methods .get_vecattr(key, attr) and .set_vecattr(key, attr, new_val) instead. See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4
> 
> I wonder how to fix this? Thank you

It seems the problem is the version of gensim, you need to change it to 3.0
